# Generated by Django 3.2.9 on 2022-01-31 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MealFindr_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eatery',
            name='comments',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MealFindr_app.comment'),
            preserve_default=False,
        ),
    ]
