# Generated by Django 3.2.9 on 2022-01-31 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealFindr_app', '0002_eatery_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eatery',
            name='comments',
        ),
        migrations.AddField(
            model_name='eatery',
            name='comments',
            field=models.ManyToManyField(to='MealFindr_app.Comment'),
        ),
    ]
