# Generated by Django 3.2.9 on 2022-01-31 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealFindr_app', '0003_auto_20220131_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(default=None, max_length=500, null=True),
        ),
    ]
