# Generated by Django 3.2.9 on 2022-01-31 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MealFindr_app', '0004_alter_comment_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eatery',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='eatery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MealFindr_app.eatery'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
