# Generated by Django 3.2.9 on 2022-01-31 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MealFindr_app', '0005_auto_20220131_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='eatery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MealFindr_app.eatery'),
        ),
    ]
