# Generated by Django 3.2.9 on 2022-02-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealFindr_app', '0008_auto_20220202_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(to='MealFindr_app.Eatery'),
        ),
    ]
