# Generated by Django 3.2.9 on 2022-02-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealFindr_app', '0011_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eatery',
            name='covidProtocol',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='eatery',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='eatery',
            name='givebackService',
            field=models.TextField(max_length=500),
        ),
    ]
